// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv_4ft5-pFUHw1h32rFXxgENpThr1eqpg',
    appId: '1:639815802167:web:90c67d448afff7788a0eb2',
    messagingSenderId: '639815802167',
    projectId: 'jarnama2example',
    authDomain: 'jarnama2example.firebaseapp.com',
    storageBucket: 'jarnama2example.appspot.com',
    measurementId: 'G-F6XRJ6EGXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUEJA22_Nctsu42k_3cy3KsfNlq0-yIVE',
    appId: '1:639815802167:android:187f61c3c6ad07df8a0eb2',
    messagingSenderId: '639815802167',
    projectId: 'jarnama2example',
    storageBucket: 'jarnama2example.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNGg-2ypVzFJnH7XyIBnC3pcJYaeiwT9Y',
    appId: '1:639815802167:ios:9a5ff1719784dca88a0eb2',
    messagingSenderId: '639815802167',
    projectId: 'jarnama2example',
    storageBucket: 'jarnama2example.appspot.com',
    iosClientId: '639815802167-mi3k4kedi45ep4unqunimdvvoqbp3i19.apps.googleusercontent.com',
    iosBundleId: 'com.example.tryCatchProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNGg-2ypVzFJnH7XyIBnC3pcJYaeiwT9Y',
    appId: '1:639815802167:ios:9a5ff1719784dca88a0eb2',
    messagingSenderId: '639815802167',
    projectId: 'jarnama2example',
    storageBucket: 'jarnama2example.appspot.com',
    iosClientId: '639815802167-mi3k4kedi45ep4unqunimdvvoqbp3i19.apps.googleusercontent.com',
    iosBundleId: 'com.example.tryCatchProject',
  );
}
